# Generated by Django 6.0.6 on 2026-06-16 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='items/')),
                ('category', models.CharField(choices=[('electronics', 'Electronics & Gadgets'), ('documents', 'IDs & Documents'), ('keys', 'Keys'), ('bags', 'Bags & Wallets'), ('clothing', 'Clothing & Accessories'), ('pets', 'Pets & Animals'), ('transport', 'Sport & Leisure'), ('kids', 'Kids & Baby'), ('other', 'Miscellaneous')], default='other', max_length=20)),
                ('type', models.CharField(choices=[('lost', 'Lost'), ('found', 'Found')], default='lost', max_length=10)),
                ('city', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('reunited', 'Reunited')], default='active', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
