# Generated by Django 6.0.6 on 2026-06-21 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_item_latitude_item_longitude_alter_item_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='city',
            field=models.CharField(default='unknown', max_length=100),
            preserve_default=False,
        ),
    ]
