# Generated by Django 6.0.6 on 2026-06-24 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_item_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='The listing will appear on the website only after approval.', verbose_name='Approved by administrator'),
        ),
    ]
