# Generated by Django 6.0.6 on 2026-07-03 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_item_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_priority',
            field=models.BooleanField(default=False),
        ),
    ]
