# Generated by Django 6.0.6 on 2026-07-13 14:22

from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_payouttransaction'),
    ]

    operations = [
        VectorExtension()
    ]
