# Generated by Django 6.0.6 on 2026-07-13 15:37

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20260713_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1024, null=True),
        ),
    ]
